### ISSUE TITLE
Private preview?

### ISSUE THREAD

**Issue by lvermeulen** [github/gh-valet#29]
## Description

How do we sign in to the private preview?

Thanks

**Comment by luke-engle** [comment]
Thanks for reaching out @lvermeulen ! Can you please work with your GitHub Account Manager to inquire about being added to the private preview?

**Comment by lvermeulen** [comment]
Hi @luke-engle thanks for your time. I believe I am my own GitHub account manager, so I asked myself and I replied that I don't know about any private preview. So how are we supposed to join this private preview?

**Comment by ethanis** [comment]
@lvermeulen apologies for the confusion! We're ironing out a process for enrolling into the private preview, but for the time being I went ahead and got you added. You should be receiving an email invite shortly that will contain links to get started.

**Comment by lvermeulen** [comment]
Thank you @ethanis !

**Comment by rsharm13** [comment]
I am also willing to sing in for this private preview. Can you please add me in?
