### ISSUE TITLE
[Support]: Error when updating valet using docker desktop on windows

### ISSUE THREAD

**Issue by gabrielecalvo** [github/gh-valet#34]
### What operating system are you using?

- [ ] Linux
- [ ] macOS
- [X] Windows

### What version of the `gh` CLI are you using?

gh version 2.10.1 (2022-05-10)
https://github.com/cli/cli/releases/tag/v2.10.1

### What version of the `gh-valet` extension are you using?

gh valet  github/gh-valet  v0.1.8

### What version of the `valet` docker container are you using?

I get the expected first-time message: 
```
Unable to locate Valet image locally. Please run `gh valet update` to fetch the latest image prior to running this command.
```
but due the issue itself I can't get the container image downloaded

### What happened?

error when running `gh valet update`:
```
> gh valet update -u gabrielecalvo -p ghp_xxxxxxxxxxxxxxx
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Error response from daemon: unauthorized
```
the docker daemon is running and I can get the `docker run hello-world` running normally

### Relevant log output

```shell
> gh valet update -u gabrielecalvo -p ghp_xxxxxxxxxxxxxxx
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Error response from daemon: unauthorized
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tattoo** [comment]
Same with me

**Comment by ethanis** [comment]
@gabrielecalvo Valet is currently private and customers must be onboarded prior to using the `gh-valet` CLI extension. Please reach out to [GitHub Sales](https://github.com/enterprise/contact) to inquire about being granted access.
