### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by prathi1** [github/gh-valet#47]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [X] Windows

### What version of the `gh` CLI are you using?

gh version 2.12.1 (2022-06-09)

### What version of the `gh-valet` extension are you using?

N/A

### What version of the `valet` docker container are you using?

N/A

### What happened?

I want to enroll in private preview and try gh-valet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ethanis** [comment]
Thanks for reach out @prathi1 ! Can you please work with your account manager or reach out to [GitHub Sales](https://github.com/enterprise/contact) to inquire about being granted access?
