### ISSUE TITLE
[Support]: Support required 

### ISSUE THREAD

**Issue by avatar321** [github/gh-valet#66]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.14.3 (2022-07-26)
gh valet        github/gh-valet v0.1.12

### What happened?

[platform@dgm010af8 ~]$ docker pull ghcr.io/valet-customers/valet-cli:latest
Error response from daemon: denied

I work for Albertson's and its GitHub enterprise customer, I was trying to pull docker image however it was throwing above error.

### Relevant log output

```shell
[platform@dgm010af8 ~]$ docker pull ghcr.io/valet-customers/valet-cli:latest
Error response from daemon: denied

Looks like unauthorized user
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luke-engle** [comment]
Hi @avatar321! 👋 

Have you followed the steps [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry) to authenticate with the GitHub docker container registry?

If so, you should be able to run `echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin` and get a successful login response

**Comment by ethanis** [comment]
@avatar321 I'm going to mark this issue as stale. If you're still having issues authenticating with Valet then please reopen 🙏
