### ISSUE TITLE
Expose new `migrate` command option `--workflow-file-prefix`

### ISSUE THREAD

**Issue by j-dunham** [github/gh-valet#76]
Valet recently added a new CLI option for the `migrate` command to add a prefix to the workflow files using `--workflow-file-path` option.  We need to reflect this change in `gh-valet`

Valet PR [link](https://github.com/github/valet/pull/4606)

**Comment by ethanis** [comment]
@j-dunham can you expose the `--commit-message` and `--github-access-token|instance-url` CLI option changes as a part of this issue too?
