### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by alexelent-carta** [github/gh-valet#94]

**Comment by alexelent-carta** [comment]
Yeah, I don't see that warning. I get an error.

```
alexelent@Alex ~ % gh extension install github/gh-valet
gh-valet unsupported for darwin-arm64. Open an issue: `gh issue create -R github/gh-valet -t'Support darwin-arm64'`
alexelent@Alex ~ % echo $?
1
```

**Comment by luke-engle** [comment]
Oh interesting.. What version of `gh` are you using? (`gh --version`)

**Comment by alexelent-carta** [comment]
```
gh version 2.4.0 (2021-12-21)
https://github.com/cli/cli/releases/tag/v2.4.0
```

**Comment by alexelent-carta** [comment]
Sigh... I figured out the issue. I am using `brew`. I had `HOMEBREW_NO_AUTO_UPDATE=1` so it didn't install latest. So sorry.

**Comment by luke-engle** [comment]
Got it, no problem! After installing the latest, are you still seeing the error?

**Comment by alexelent-carta** [comment]
Nope, error is gone on latest version of gh cli (2.18.1)
